# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+Title: Especificação do Trabalho Final de MLP 2018/1
#+Author: Prof. Lucas Mello Schnorr (INF/UFRGS)
#+Date: schnorr@inf.ufrgs.br

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt, a4paper]
#+LATEX_HEADER: \input{org-babel.tex}

#+OPTIONS: toc:nil
#+STARTUP: overview indent
#+TAGS: Lucas(L) noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

* Sumário
** Geral

| Item          | Descrição                                                    |
|---------------+--------------------------------------------------------------|
| Grupos        | Três alunos                                                  |
| Linguagem     | Uma dentre aquelas listadas                                  |
| Problema      | Um dentre aqueles sugeridos                                  |
| Implementação | Duas: OO e funcional, cada uma com paralelismo               |
| Relatório     | Um com os requisitos obrigatórios (=latex= e =bibtex=) -- [[https://github.com/schnorr/mlpreport][Modelo]] |
| Submissão     | ZIP ou TAR.GZ, por e-mail, com [[https://filesender.rnp.br/][FileSender da RNP]]             |

** Prazos

#+BEGIN_CENTER
Os prazos são até às 23:59 do dia informado.
#+END_CENTER

| Item                            |      Prazo |
|---------------------------------+------------|
| Anúncio (Início do TF)          | 2018-08-29 |
| Escolha da LP, Problema, Grupos | 2018-09-05 |
| Projeto inicial                 | 2018-09-12 |
| Entrega *parcial*                 | 2018-10-22 |
| Entrega *final*                   | 2018-11-14 |
| Apresentações Sessão #1         | 2018-11-26 |
| Apresentações Sessão #2         | 2018-11-28 |

* Visão Geral e Linguagens

O objetivo deste trabalho consiste em fornecer aos alunos a
oportunidade de *estudar uma linguagem de programação moderna com
características híbridas* (i.e., multiparadigma). O trabalho permitirá
aos alunos *demonstrarem que aprenderam os princípios de programação
relacionados com os diferentes paradigmas* estudados ao longo do
semestre, demonstrando, ainda, a *capacidade de analisar e avaliar
linguagens de programação, seguindo os critérios abordados em aula*.

Cada grupo *deve selecionar uma linguagem de programação da lista
abaixo*. Cada linguagem poderá ser escolhida por no máximo dois
grupos. A ordem de preferência da escolha da linguagem será por
sorteio, no cenário onde mais de dois grupos estejam interessados na
mesma linguagem. A escolha do grupo deve ser realizada dentro do prazo
estabelecido.

| C++17          | [[https://isocpp.org/std/status][ISO-CPP]]                         |
| Clojure        | http://clojure.org/             |
| Erlang         | http://www.erlang.org/          |
| Julia          | http://julialang.org/           |
| Kotlin         | https://kotlinlang.org          |
| Objective CAML | http://ocaml.org/               |
| R              | https://www.r-project.org/      |
| Ruby           | http://ruby-lang.org/           |
| Rust           | https://www.rust-lang.org/      |
| Scala          | http://www.scala-lang.org/      |

A tarefa principal do trabalho consiste em experimentar e comparar as
características e funcionalidades orientadas a objeto e funcionais da
linguagem de programação escolhida. Após definir um grupo e selecionar
uma linguagem, é necessário escolher um problema a ser solucionado com
ela.  O problema será, então, implementado *duas vezes na mesma
linguagem*: uma delas usando *somente* Orientação a Objetos e a outra
usando *somente* características funcionais. Interfaces (gráficas ou
textuais) podem ser feitas em qualquer paradigma ou plataforma,
podendo inclusive serem compartilhadas entre as duas versões, visto
que o foco não está na interface do programa.

* Definição dos grupos, do problema e da linguagem

Cada grupo é formato com três participantes e elege um líder. O líder
informa ao professor, via formulário abaixo, qual o problema
escolhido, a linguagem, e os membros do grupo. Grupos com outra
quantidade de membros são aceitos somente para fins de arrendondamento
da turma (converse com o professor antes).

|------------------------------------|
| [[https://goo.gl/forms/cJz0v618SYpoqr153][Formulário de definição dos grupos]] |
|------------------------------------|

* Problemas disponíveis
** Jogo pedagógico

Implementar um jogo pedagógico, com o objetivo de ajudar qualquer
pessoa a aprender um conceito, seja este de qualquer nível. O jogo
deve ter interatividade com o seu usuário, e algumas telas que
demonstram o conceito que está querendo se passar, do básico ao
complexo. Sugere-se adicionalmente que o jogo tenha um cunho
colaborativo ao invés de competitivo.

** War

A ideia é desenvolver um jogo de batalha por turnos estilo o jogo
americano [[http://en.wikipedia.org/wiki/Risk_(game)][Risk]], a versão Brasileira [[http://pt.wikipedia.org/wiki/War][War]]. A fim de tornar o jogo menos
complexo e menos demorado, sua versão pode envolver somente dois
adversários (seja outro ser humano ou o
computador). Preferencialmente, o jogo pode utilizar os tiles do
OpenStreetMap para desenhar o mapa e posicionar exércitos.

** MarioBrosAI                                                    :noexport:

A ideia consiste em desenvolver um software (bot ou agente) que
controle o personagem Mário Bros para o ambiente InfiniteMarioBros,
utilizado na [[http://julian.togelius.com/mariocompetition2009/][Mario AI Competition]]. O Mário deve coletar o maior número
de moedas no menor espaço de tempo, sem morrer.

** Starcraft

A ideia consiste em desenvolver um software (bot ou agente) que
controle um exército para competir no jogo Starcraft Broodwar. Maiores
detalhes em: http://sscaitournament.com/ e
https://github.com/bwapi/bwapi.

** BatalhaNaval                                                   :noexport:

O computador deve sortear uma configuração ao inicial do jogo, em que
estarão colocados num tabuleiro de tamanho 15x15 os seguintes itens: 4
submarinos (2 casas), 3 navios (3 casas) e 5 minas (1 casa cada). Em
cada jogada, o computador lê as coordenadas (linha e coluna) da casa
em que o usuário quer atingir e indica o resultado, ou seja, se
acertou na água ou em parte de um navio (navio inteiro se for uma
mina).  O jogo termina quando o usuário afundar toda a frota, ou
quando indicar que não quer continuar a jogar. Ao invés de solicitar
as coordenadas, você pode usar o mouse como entrada de dados.

** TowerDefence                                                   :noexport:

Neste tipo de jogo você precisa defender algum elemento ou posição na
tela, normalmente em algum cenário composto de uma ou mais estradas ou
caminhos que são percorridos por uma série de inimigos (por rounds). A
cada round você tem um saldo a gastar em torres ou elementos de defesa
(ou ainda em \url{upgrades}), que podem ser posicionados em locais
fixos ou abertos ao longo do cenário. Esses elementos de defesa devem
atacar os inimigos, destruindo-os antes que cheguem ao alvo. Cada
inimigo tem um poder de ataque, cura ou quantidade de vida específico,
o qual diminui cada vez que recebe algum tiro de defesa. Cada vez que
um inimigo é acertado ou morto, você ganha créditos. O jogo termina
quando uma quantidade x de inimigos chega no objetivo ou quando seu
ponto de defesa fica muito fraco. Maiores detalhes em:
\url{http://en.wikipedia.org/wiki/Tower_defense/}.

** Escopo

Ou seja, desenvolver um simulador capaz de aceitar definições de
subprogramas e variáveis locais, utilizando uma pseudolinguagem
simples. Com base nisso, demonstrar como ficaria sua pilha de chamadas
(call-stack) e o conteúdo das variáveis locais a cada passo de
execução.

** Simulador de Galáxias

Implementar um simulador de partículas, considerando forças físicas de
repulsão e atração. Uma possibilidade é utilizar as leis
gravitacionais para construir um simulador de órbitas para estrelas e
planetas. Outra possibilidade é utilizar uma força elétrica de
repulsão (todas as partículas com carga positiva, por exemplo), e
forças de atração baseadas em molas. Deve-se ter cuidado com a
escalabilidade do algoritmo utilizando, dando preferências para o
algoritmo de Barnes-Hut. Um exemplo utilizando a linguagem C já está
disponível em http://github.com/schnorr/viva/tree/master/src/libtupi,
e pode ser utilizado como inspiração para o projeto.

** Frogger

Frogger é um jogo arcade de 1981 onde o objetivo é realizar o
cruzamento de sapos (a partir da parte inferior da tela) em uma
estrada e depois em um rio até ocupar todos os espaços (na parte
superior da tela). Existem vários obstáculos que devem ser evitados
(ou utilizados para se atingir o objetivo) como carros, pedaços de
madeira, tartarugas, jacarés, etc. Os obstáculos se movem com
diferentes velocidades. [[https://froggerclassic.appspot.com/][Mais informações aqui]] e na [[https://pt.wikipedia.org/wiki/Frogger][Wikipedia Frogger]]
(entrada em inglês mais completa).

** Space Invaders

O jogo expõem o jogador como uma espaçonave que deve destruir as
espaçonavas inimigas que querem invadir o planeta do jogador. Na
medida que elas avançam na tela (de cima para baixo), o jogador guia
sua espaçonave (de maneira livre na tela mas sempre realizando
disparos em direção ao alto da tela), para destruir todas as ondas de
inimigos que se seguem. [[http://www.pacxon4u.com/space-invaders/][Mais informações aqui]] e na
[[https://pt.wikipedia.org/wiki/Space_Invaders][Wikipedia Space Invaders]].

** Editor de Polígonos

Construir um editor de polígonos interativo parecido com a ferramenta
vetorial de código aberto [[https://inkscape.org][Inkscape]]. O editor deve permitir ao usuário
editar polígonos através de todos os pontos do seu perímetro, assim
como realizar operações clássicas como alinhamento de objetos,
centralização, cálculo de área e extensão do perímetro.

** Processamento de dados                                         :noexport:

Construir um programa de mineração ou processamento de dados, onde os
dados são colocados na entrada de maneira continua e o sistema deve
realizar operações estatísticas sobre eles.

** Escolhendo um problema pessoal

No caso, o grupo deve encaminhar sua ideia ao professor, descrita em
detalhes, que avaliará sua viabilidade.
* Recursos Necessários (critérios mínimos)

O trabalho realizado *deve considerar os aspectos especificados nesta
seção*, sendo um conjunto específico de recursos para a solução
orientada a objetos e outro para a solução funcional. Caso um recurso
não esteja disponível na linguagem, *explique e justifique* no relatório
os motivos para ele não existir *e utilize um mecanismo alternativo*. Os
recursos de processamento paralelo _devem aparecer tanto na
implementação orientada a objetos quando na solução funcional_.

** Requisitos de orientação a objetos

- Especificar e utilizar classes (utilitárias ou para representar as
  estruturas de dados utilizadas pelo programa).
- Fazer uso de encapsulamento e proteção dos atributos, com os devidos
  métodos de manipulação (setters/getters) ou propriedades de acesso,
  em especial com validação dos valores (parâmetros) para que estejam
  dentro do esperado ou gerem exceções caso contrário.
- Especificação e uso de construtores-padrão para a inicialização dos
  atributos e, sempre que possível, de construtores alternativos.
- Especificação e uso de destrutores (ou métodos de finalização),
  quando necessário.
- Organizar o código em espaços de nome diferenciados, conforme a
  função ou estrutura de cada classe ou módulo de programa.
- Usar mecanismo de herança, em especial com a especificação de pelo
  menos três níveis de hierarquia, sendo pelo menos um deles
  correspondente a uma classe abstrata, mais genérica, a ser
  implementada nas classes-filhas.
- Utilizar polimorfismo por inclusão (variável ou coleção genérica
  manipulando entidades de classes filhas, chamando métodos ou funções
  específicas correspondentes).
- Usar polimorfismo paramétrico
  - através da especificação de \textit{algoritmo} (método ou função
    genérico) utilizando o recurso oferecido pela linguagem (i.e.,
    generics, templates ou similar)
  - e da especificação de \textit{estrutura de dados} genérica
    utilizando o recurso oferecido pela linguagem.
- Usar polimorfismo por sobrecarga (vale construtores alternativos).
- Especificar e usar delegates.      
   
** Recursos para a solução funcional
- Priorizar o uso de elementos imutáveis e funções puras (por exemplo,
  sempre precisar manipular listas, criar uma nova e não modificar a
  original, seja por recursão ou através de funções de ordem maior).
- Especificar e usar funções não nomeadas (ou lambda).
- Especificar e usar funções que usem currying.
- Especificar funções que utilizem pattern matching ao máximo, na sua
  definição.
- Especificar e usar funções de ordem superior (maior) criadas pelo
  programador.
- Usar funções de ordem maior prontas (p.ex., map, reduce, foldr/foldl
  ou similares).
- Especificar e usar funções como elementos de 1ª ordem.    
- Usar recursão como mecanismo de iteração (pelo menos em funções de
  ordem superior que manipulem listas).
  
** Recursos de processamento paralelo

# - Definição, uso e gerência de streams (de preferência, com recursos
#  funcionais, i.e., funções de alta ordem e anônimas) para o
#  processamento de dados
- Definição, uso e gerência de unidades (threads, módulos, classes,
  métodos, funções, trechos ou instruções) de execução concorrente e o
  seu sincronismo
- Definição, uso e gerência de regiões críticas (variáveis, arrays,
  coleções ou similares)

* Relatório

O grupo deve apresentar um relatório técnico com os itens descritos
abaixo. O relatório deve ser escrito utilizando a linguagem =LaTeX=. O
modelo do relatório pode ser obtido aqui:
- https://github.com/schnorr/mlpreport

Segue a lista dos itens obrigatórios para o relatório:

1. Capa: com identificação do grupo, da linguagem e do problema escolhidos.
2. Visão geral da Linguagem: Apresentação da linguagem escolhida,
   descrevendo suas características, fundamentos, funcionalidades,
   benefícios e principais aplicações (inclusive com discussão de sua
   aplicabilidade em questões práticas).
3. Recursos: esta seção deve descrever cada um dos recursos que foram
   empregados nas duas soluções (OO e Funcional), incluindo trechos de
   código implementados pelo grupo e utilizados na solução final. Os
   requisitos de processamento paralelo devem estar descritos nas duas
   implementações.  Recomenda-se o uso do pacote =listings= (Latex) para
   a inclusão de código no relatório. Todos os trechos de código devem
   ser explicados na língua utilizada para redigir o documento.
4. Análise Crítica: uma análise crítica da linguagem estudada,
   envolvendo uma tabela com os critérios e propriedades estudados em
   aula (i.e. simplicidade, ortogonalidade, expressividade,
   adequabilidade e variedade de estruturas de controle, mecanismos de
   definição de tipos, suporte a abstração de dados e de processos,
   modelo de tipos, portabilidade, reusabilidade, suporte e
   documentação, tamanho de código, generalidade, eficiência e custo,
   e outros que o grupo achem convenientes), com notas/valores
   justificados (ilustrando com exemplos utilizados no código ou
   descrevendo situações que contariam como pontos favoráveis ou
   desfavoráveis para cada critério ou propriedade). Indicar qual
   paradigma foi mais adequado para resolver o problema e por que.
5. Melhoramentos: o grupo deve sugerir mudanças que melhorem a
   linguagem naqueles pontos que o grupo identificou como
   problemáticos. Na ausência de pontos problemáticos (o que raramente
   será o caso), o grupo deve sugerir melhoramentos que permitam
   a linguagem evoluir sob todos os aspectos.
6. Conclusão: descrevendo as facilidades e dificuldades encontradas,
   benefícios, problemas e limitações da linguagem estudada.
7. Referências: todo material consultado, incluindo livros, artigos,
   páginas na Internet, etc., que tenha relação com o
   assunto. Elaborar a lista usando =bibtex=.

Não serão aceitos trabalhos com indícios de plágio (cópia integral ou
parcial de outros trabalhos). Utilizar trechos e exemplos, mesmo que
em forma de paráfrase, é permitido e estimulado, desde que a menção
(citação) ao autor do original seja feita corretamente.

* Boas práticas

Sugere-se adoção destas técnicas para a execução deste trabalho.

- GIT: para gerenciar o desenvolvimento em grupo e manter um
  repositório único de código, permitindo não só gerenciar versões,
  mas também controlar a contribuição de cada participante.
- Máquina Virtual: para que você possa configurar todas as
  bibliotecas, plug-ins e componentes necessários para o
  desenvolvimento e a execução de seu software.

* Etapas de Entrega

Todas as etapas de entrega deverão ser encaminhados até a data
estipulada pelo professor por e-mail, e são obrigatórias. As entregas
devem ser realizadas através de um arquivo compactado (ZIP ou TAR.GZ),
contendo o relatório (em PDF) e os códigos-fontes desenvolvidos (não
incluir os códigos binários). Utilize o serviço [[http://filesender.rnp.br][FileSender da RNP]] para
envio de arquivos grandes, mediante login utilizando o cartão do aluno
da UFRGS.

** Projeto Inicial

O *projeto inicial*, uma etapa obrigatória, deve vir acompanhada apenas
da capa, introdução e da apresentação da linguagem escolhida e do
problema. Sugere-se que uma estrutura completa do relatório já esteja
igualmente presente.

** Entrega Parcial

A *entrega parcial*, uma etapa obrigatória, deve vir acompanhada da
implementação e relatório a respeito da solução utilizando um dos
paradigmas (OO ou funcional) com paralelismo, a critério do grupo. O
professor utilizará esta oportunidade para formar um parecer rápido do
relatório e da implementação; sugerindo ao grupo melhorias caso
necessário.

** Entrega Final

A *entrega final* incorpora os comentários do parecer do professor das
entregas anteriores e a implementação e relatório nos dois paradigmas
(OO e funcional) com paralelismo em cada um deles. É a entrega final
que será utilizada para a avaliação, conforme método descrito abaixo.

* Apresentação

A apresentação do trabalho prático será feita diante da turma e do
professor nas aulas especificadas no cronograma da disciplina. Cada
grupo terá 10 minutos para a apresentação. Dentro desse tempo, os
alunos deverão: apresentar o problema, apresentar a linguagem
escolhida para a implementação, apresentar quais foram as vantagens e
desvantagens da abordagem OO e da funcional para a implementação da
solução do problema, detalhar os melhoramentos que foram sugeridos e,
por fim, fazer uma breve demonstração. O professor fará perguntas
pontuais direcionadas para cada um dos membros do grupo. A
apresentação faz parte da nota. Pontualidade e participação na
apresentação dos colegas também.

* Nota
Os alunos que estão repetindo a disciplina, por qualquer razão, devem
obrigatoriamente escolher uma combinação linguagem/problema diferente
daquela que foi escolhida nas edições anteriores.
* Avaliação

A avaliação geral do trabalho incluirá os seguintes critérios:
desenvolvimento e detalhamento dos itens do relatório, aplicação dos
conceitos de programação estudados, utilização correta dos recursos da
linguagem escolhida, correção, legibilidade, confiabilidade e
originalidade, uso de referências, formatação e estilo do
texto. Outros aspectos de avaliação poderão ser incluídos a critério
do professor. O peso deste trabalho corresponde ao valor especificado
no plano da disciplina disponível na plataforma de apoio pedagógico.

*Atenção*: conforme instruções presentes no plano de ensino da
disciplina, todas as etapas do trabalho devem ser cumpridas para que a
sua nota de trabalho seja contabilizada!
