all:
	+$(MAKE) -C aulas/excecoes
	+$(MAKE) -C aulas/fluxo
	+$(MAKE) -C aulas/funcional
	+$(MAKE) -C aulas/geral
	+$(MAKE) -C aulas/monte
	+$(MAKE) -C aulas/oo
	+$(MAKE) -C aulas/paralela
	+$(MAKE) -C aulas/polimorfismo
	+$(MAKE) -C aulas/prolog
	+$(MAKE) -C aulas/r
	+$(MAKE) -C aulas/script
	+$(MAKE) -C aulas/subprogramas
	+$(MAKE) -C aulas/tipos
	+$(MAKE) -C aulas/vinculos
