* Conjunto de Atividades Teórico-Práticas (CATP)

Todos os prazos são até as 23:59 da data informada.

Existem duas formas de entrega, em papel e por e-mail. A forma de
entrega específica de cada CATP está listada na tabela abaixo. Caso o
campo esteja vazio, isso indica que a entrega é por e-mail. Quando a
entrega é por papel, este deve ser entregue em mãos antes do prazo
especificado. Quando a entrega é por e-mail, este deve ser enviado
antes do prazo especificado com o título "CATP #NN", onde NN são os
dois digítos que identificam o CATP.

Somente serão válidos os relatórios textuais em arquivos do tipo TXT
ou PDF. Código fonte em arquivos com codificação UTF8, ou diretamente
no corpo do e-mail quando o resultado do CATP é pequeno. E lembre-se:
todos os CATP devem ter uma identificação clara dos participantes, em
todos os arquivos enviados.

Quando a entrega for por =Email (corpo)=, siga este método:
- Escreva um e-mail para o professor @INF
- O título do e-mail deve ser =CATP #DD=
  - Onde =DD= são os dois dígitos que identificam o CATP
- A solução deve estar no corpo do e-mail (e _não em anexo_)
- No início do corpo do e-mail, a mensagem deve ter
  - "# Aluno: ..." ou
  - "# Aluna: ..."
  - Após o dois pontos, coloque o *nome completo*

| CATP | Descrição                       | Entrega       |      Prazo | Resultado |
|------+---------------------------------+---------------+------------+-----------|
| #01  | [[./01/formulario.pdf][Formulário de Avaliação de LPs]]  | Papel/Email   | 2017-08-30 |           |
| #02  | [[./02/README.org][Listas e recursividade em R]]     | Email (corpo) | 2017-09-06 | [[./eval/02/README.org][Relatório]] |
| #03  | [[./03/README.org][Recursividade e funcionais em R]] | Email (corpo) | 2017-09-11 | [[./eval/03/README.org][Relatório]] |

